config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sounds#index'

  resources :sounds do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  post '/sounds/new' => 'sounds#create'
   
  # ゲストログイン機能追加時に追記
  post '/sounds/guest_sign_in', to: 'sounds#new_guest'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sound
  belongs_to :user

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '専門家・プロ' },
    { id: 3, name: '著名人・インフルエンサー' },
    { id: 4, name: '人・ライフスタイル' },
    { id: 5, name: 'ニュース・語学' },
    { id: 6, name: 'ラジオ・トーク' }
  ]
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :sound
  belongs_to :user
  validates_uniqueness_of :sound_id, scope: :user_id
end

app/models/sound.rb
class Sound < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  # carrierwave導入後のuploderをジェネレート時に追記
  mount_uploader :file, AudiofileUploader

  def self.search(search)
    if search != ''
      Sound.where('text LIKE(?) OR title LIKE(?)', "%#{search}%", "%#{search}%")
      # OR Sound.joins(:user).where('nickname LIKE(?)', "%#{search}%")
    else
      Sound.all
    end
  end

  with_options presence: true do
    validates :file
    validates :title, length: { maximum: 40 }
    validates :text, length: { maximum: 1000 }
    validates :genre_id, numericality: { other_than: 0, message: 'は選択しないと投稿できません' }
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sounds, dependent: :destroy
  has_many :comments
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_sounds,  through: :likes, source: :sound

  def already_liked?(sound)
    likes.exists?(sound_id: sound.id)
  end

  with_options presence: true do
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
    validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    validates :nickname, uniqueness: true
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{6,100}+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'
    validates :image
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64(10)
      user.nickname = 'ゲストさん'
      # user.image = fixture_file_upload('public/testimages/test_image02.jpg')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/sounds/#{comment.sound_id}"
  end

  def index
    @comments = Comment.all(order: 'created_at DESC')
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, sound_id: params[:sound_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(sound_id: params[:sound_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(sound_id: params[:sound_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:edit, :show, :update, :destroy]
  # before_action :move_to_index, except: [:index,:search], notice: 'ログインしてください'
  # before_action :authenticate_user!, except: [:index, :search]

  def index
    @sounds = Sound.includes(:user).order('created_at DESC')
  end

  def new
    @sound = Sound.new
  end

  def create
    @sound = Sound.new(sound_params)
    if @sound.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @sound.update(sound_params)
      redirect_to root_path
    else
      rendar :edit
    end
  end

  def destroy
    if @sound.destroy
      redirect_to root_path
    else
      rendar :edit
    end
  end

  def show
    if user_signed_in?
      @sound = Sound.find(params[:id])
      @comment = Comment.new
      @comments = @sound.comments.includes(:user)
      @like = Like.new
    else
      redirect_to root_path, notice: 'ログインしてからご利用下さい。'
    end
  end

  def search
    @sounds = Sound.search(params[:keyword])
  end

  # ゲストログイン機能追加時に追記
  def new_guest

    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64(10)
      user.nickname = 'ゲストさん'
      user.image = has_one_atacched:'public/testimages/test_image02.jpg'
    end

    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  private

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end

  def sound_params
    params.require(:sound).permit(:file, :title, :text, :genre_id).merge(user_id: current_user.id)
  end

  def set_sound
    @sound = Sound.find(params[:id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Talky_Mine ~人生を彩るサウンドメディア~</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%# <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico" /> %>
  <link rel="shortcut icon" type="image/x-icon" href="/puclic/favicon.ico" />
  
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag "item-sample.png", class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= "商品説明" %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= 999,999,999 %></p>
          <p class='item-price-sub-text'>（税込）送料込み</p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= "販売価格" %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area 'hoge', class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field "hoge",class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <%# 配送先の入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>
        配送先入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field 'hoge', class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# /配送先の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <%= link_to image_tag("TM-logo-white.png", class:"logo-white"), "#" %>
 
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>

  <div class='search-bar-contents'>
    <%= link_to image_tag("TM-logo-color.png", class:"furima-icon"), "/" %>
    <%= form_with url: search_sounds_path, local: true, method: :get, class:"search-form" do |form|  %>
      <%= form.text_field :keyword, placeholder: 'チャンネル/パーソナリティ名', class:'input-box' %>
      <%= form.submit "検索", class:"search-button" %>
    <% end %>

    <%# <div class='player'> %>
    
    <div class='nav'>
      <ul class='lists-right'>
         <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <%
=begin%>
 <li><%= link_to 'ゲストログイン（閲覧用）', sounds_guest_sign_in_path,class: "sign-up", method: :post %></li> 
<%
=end%>
        <% end %>
      </ul>
    </div>
  </div>
  
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "TM-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("TM-logo-color.png", class:"second-logo"), "/" %>
</header>

app/views/sounds/_sound.html.erb
       <li class='list'>
         <%= link_to sound_path(sound.id) do %>
         <div class='item-img-content'>
           <%= image_tag sound.user.image, class: "sound-img" %>
          </div>
          <% end %>
 
          <div class='sound-info'>
            <h4 class='sound-name'>
              <%= sound.user.nickname %>
            </h4>
            <h5 class='sound-name'>
              <%= sound.title %>
            </h5>
            <div class='sound-price'>
              <div class='star-btn'>
                <%= image_tag "heart-icon.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
      </li>

app/views/sounds/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='main-contents'>  
   <%# ①メニューバー %>
   <div class='menu'>
     <ul>
       <li>ユーザーネーム</li>
       <li>ログアウト</li>
       <li>フォロー中</li>
       <li>おすすめチャンネル</li>
     </ul>
   </div>
   <%# /①メニューバー %>

   <%# ②投稿一覧 %>
   <div class='sound-contents'>

     <%# <h2 class='title'>ピックアップカテゴリー</h2> %>
     <%= link_to '新着放送', "/sound/new", class: "subtitle" %>
     <ul class='sound-lists'>
   
    <% if @sounds.length != 0 %>
      <% @sounds.each do |sound|%>
       <li class='list'>
         <%= link_to sound_path(sound.id) do %>
         <div class='item-img-content'>
           <%= image_tag sound.user.image, class: "sound-img" %>
          </div>
          <% end %>
 
          <div class='sound-info'>
            <h4 class='sound-name'>
              <%= sound.user.nickname %>
            </h4>
            <h5 class='sound-name'>
              <%= sound.title %>
            </h5>
            <div class='sound-price'>
              <div class='star-btn'>
                <%= image_tag "heart-icon.png", class:"star-icon" %>
                <span class='star-count'><%= sound.liked_users.count %></span>
              </div>
            </div>
          </div>
      </li>
    <% end %>

       <%# //商品のインスタンス変数になにか入っている場合、中身のすべてを展開できるようにしましょう %>
   
       <%# 商品がない場合のダミー %>
       <% else %>
       <%# 商品がある場合は表示されないようにしましょう %>
       <li class='list'>
         <%= link_to '#' do %>
         <%= image_tag "https://4.bp.blogspot.com/-pwFCxy4007s/WMfCNtlUzAI/AAAAAAABClg/B-YK7BXBGAAyW2Lilrkl48zqryJUAUlLgCLcB/s800/onsei_ninshiki_computer.png", class: "sound-img" %>
         <div class='sound-info'>
           <h3 class='sound-name'>
             音声を投稿してね！
           </h3>
             <div class='star-btn'>
               <%= image_tag "heart-icon.png", class:"star-icon" %>
               <span class='star-count'>0</span>
             </div>
           </div>
         
        <% end %>
       </li>
       <%# //商品がある場合は表示されないようにしましょう %>
       <%# /商品がない場合のダミー %>
     </ul>
    <% end %>
   </div>
   <%# /②投稿一覧 %>

   <%# ③ランキング %>
   <div class='ranking'>
   ここはランキング
   </div>
   <%# /③ランキング %>

  </div>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>投稿する</span>
  <% if user_signed_in? %>
  <a href="/sounds/new/">
  <% else %>
  <a href="/users/sign_in/">
  <% end %>
      <%= image_tag 'mic-icon.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>

<%= render "shared/footer" %>

app/views/sounds/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('TM-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿の情報を入力</h2>
    <%= form_with model: @sound, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 投稿音源 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        投稿音声ファイル
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.label :file %>
        <%= f.file_field :file%>
      </div>
    </div>
    <%# /出品画像 %>

    <%# 投稿名と内容説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        投稿名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"投稿タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          投稿の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"投稿内容の説明（必須 1,000文字まで）（テーマ、対象、注意点など）例）来年に向けて今年を振り返ります。今年の実績は主に◯◯です。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /投稿名と内容説明 %>

    <%# 投稿の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">投稿の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"sound-category"}) %>        
      </div>
    </div>
    <%# /投稿の詳細 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている投稿内容、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">ユーザー規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="footer-menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('TM-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Talky-Mine,Inc.
    </p>
  </footer>
</div>

app/views/sounds/search.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='main-contents'>  
   <%# ①メニューバー %>
   <div class='menu'>
   ここはメニューバー
   </div>
   <%# /①メニューバー %>

   <%# ②投稿一覧 %>
   <div class='sound-contents'>
     <%= link_to 'トップへ戻る', "/#", class: "subtitle" %>
      <ul class='sound-lists'>
      <% @sounds.each do |sound|%>
        <%= render partial: "sound", locals: { sound: sound } %>
      <% end %>
      </ul>
   </div>

   <%# ③ランキング %>
   <div class='ranking'>
   ここはランキング
   </div>
   <%# /③ランキング %>

  </div>
</div>
<div class='purchase-btn'>
  <span class='purchase-btn-text'>投稿する</span>
  <% if user_signed_in? %>
  <a href="/sounds/new/">
  <% else %>
  <a href="/users/sign_in/">
  <% end %>
      <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  </a>
</div>

<%= render "shared/footer" %>

app/views/sounds/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-all" >
  <div class="item-show">
  
    <%# ①メニューバー %>
    <div class='menu'>
      <ul>
        <li>ユーザーネーム</li>
        <li>ログアウト</li>
        <li>フォロー中</li>
        <li>おすすめチャンネル</li>
      </ul>
    </div>
    <%# /①メニューバー %>
  
    <%# /②投稿の概要 %>
    <div class="item-box">
        <%# <div class="item-box-img">
          <%= image_tag @sound.user.image%>
        <%# </div> %> 

        <%# <div class="item item--first">
          <%= image_tag @sound.user.image%>
        <%# </div> %> 

  
          <%= image_tag @sound.user.image, class:"item-box-img"%>
      





  
      <%# リスナーユーザーとパーソナリティーユーザーで処理分岐 %>
      <% if  user_signed_in? && current_user.id == @sound.user_id %>
      <%= link_to '投稿の編集', "#", method: :get, class: "item-red-btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', "#", method: :delete, class:'item-destroy' %>
      <% end %>
      <%# /リスナーユーザーとパーソナリティーユーザーで処理分岐 %>
   
      <div class="LR-box">
        <div class="L-box">
           <span><%= image_tag @sound.user.image, class:"sound-user-img"%></span>
           <span><%= @sound.user.nickname %></span>
           <div>
              <% if current_user.already_liked?(@sound) %>
               <%= button_to 'いいねを取り消す', sound_like_path(@sound), method: :delete, class:"favorite-btn"%>
              <% else %>
               <%= button_to 'いいね', sound_likes_path(@sound),class:"favorite-btn" %>
              <% end %>
            </div>
        </div>
        <div class="R-box">
            <h2 class="name">
              <%= @sound.title%>
            </h2>
            <span class="genre"><%= @sound.genre.name%></span>
            <span><%= @sound.text %></span>
            <audio src= "<%= @sound.file.url  %>" controls="" class="sound-audio">
             <a src= "<%= @sound.file.url %>">ダウンロード</a>
             <p>音声を再生するには、audioタグをサポートしたブラウザが必要です。</p>
            </audio>

        </div>


      </div>
     

     
    </div> 
    <%# /②投稿の概要 %>
  
    <%# ③ランキング %>
    <div class="right-bar">
      <div class="comment-box">
        <% if current_user %>
          <%= form_with model: [@sound,@comment], local: true do |f| %>
            <%= f.text_area :text, placeholder: "コメントする" %>
            <p class="comment-warn">
              相手のことを考え丁寧なコメントを心がけましょう。
              <br>
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            </p>
            <%= f.submit "SEND" %>
          <% end %>
          <%else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
      </div>
      <div class="comments">
          <h4>＜コメント一覧＞</h4>
          <% if @comments %>
            <% @comments.each do |comment| %>
              <p>
                <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
                <%= comment.text %>
              </p>
            <% end %>
          <% end %>
      </div>
       
      
      <div class="option">
        <div>
          <%= image_tag "heart-icon.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
          <span><%= @sound.likes.count %></span>
        </div>
      </div>
  
      <div>  
          <h3>いいねしたユーザー</h3>
          <% @sound.liked_users.each do |user| %>
           <li><%= user.nickname %></li>
          <% end %>
      </div>
    </div>
    <%# /③ランキング %>
  
    
  
  </div class="item-show">

</div>
<%= render "shared/footer" %>